### ISSUE TITLE
PhotoBrowser has multiple issues with PushState

### ISSUE THREAD

**Issue by sepehrr** [framework7io/framework7#1061]
This is a (multiple allowed):
- [x] bug
- [ ] enhancement
- [ ] feature-discussion (RFC)
- Framework7 Version: 1.4.4
- Platform and Target: Seen on Browser and Cordova (android), both material and ios design, most likely happens other places
### What you did No.0

Using the kitchen sink, edited kitchen-sink.js and put `pushState:true,` parameter for myApp variable. just this.

Now I saw multiple problems when I used PhotoBrowser and used back-button (on android, or back-button on browser).
### What you did No.1

I clicked on PhotoBrowser, then clicked "PAGE" button, photobrowser opened correctly, I closed it using back-button and came back to previous page, once again I clicked on "PAGE" button,
### Expected Behavior No.1

PhotoBrowser be openned again.
### Actual Behavior No.1

Nothing happened!

---
### What you did No.2

I clicked on PhotoBrowser, then clicked "PAGE" button, photobrowser opened correctly, I click on photo to hide navbar, then I closed it using back-button and came back to previous page
### Expected Behavior No.2

Previous page rendered correctly
### Actual Behavior No.2

navbar on the previous page is gone too! (It didn't came back after pressing back-button!)

---
### What you did No.3

I clicked on PhotoBrowser, then clicked "STANDALONE/POPUP" button, photobrowser opened correctly, I clicked on back-button
### Expected Behavior No.3

PhotoBrowser be closed.
### Actual Behavior No.3

Photobrowsers stays on and instead back-button  affected previous page(went to Index.html)

**Comment by sepehrr** [comment]
My own solution for Bug.No.1:
create a PhotoBrowser object every time solves the problem

My own solution for Bug.No.2:
I use F7 with Cordova, so I did something like this:
```
document.addEventListener("backbutton", onBackKeyDown, false);

function onBackKeyDown() {
    try{ myPhotoBrowserPage.disableExposition(); }catch(e){}
    mainView.router.back();
}
```
in code above, onBackKeyDown, before navigating to previous page, I disable PhotoBrowser's exposition so navbar become visible and problem is solved.

My own solution for Bug.No.2:
use a variable to check if PhotoBrowser is opened and onBackKeyDown check variable. if PhotoBrowser was opened, close it, else navigate to previous page.

**Comment by valnub** [comment]
I can confirm bugs 1 and 2, but not bug 3.

**Comment by tinyCoder32** [comment]
Oh god, finally.
Number 2 is what i'm seeking for long time!
I have reported and thought it is caused by something else, now I see that the photo browser is the reason:

https://github.com/nolimits4web/Framework7/issues/1338

**Comment by devgeeks** [comment]
Can confirm bug 2 still exists. Would it be possible to try and close the exposition in `onClose` instead of directly in the back button handler? Otherwise it only fixes it for android, not in a browser (like a PWA, etc).

Note I am using F7-Vue.

**Comment by nolimits4web** [comment]
Issue is closed because of outdated/irrelevant/not actual

If this issue is still actual and reproducible for latest version of Framework7, please create new issue and fill the issue template correctly:
* Clearly describe the issue including steps to reproduce when it is a bug.
* Make sure you fill in the earliest version that you know has the issue.
* Provide live link or JSFiddle/Codepen or website with issue
