### ISSUE TITLE
Button freezing on MD 

### ISSUE THREAD

**Issue by EriveltonMS** [framework7io/framework7#2418]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* Framework7 Version:  Framework7 2.2.5
* Platform and Target: CORDOVA ANDROID.

### What you did
Create left panel on app. Programming was not used, only the standard framework css. I used the panel of the template itself to create my model.

`<div class="panel panel-left panel-cover theme-dark">
      <div class="view">
        <div class="page">
          <div class="navbar">
            <div class="navbar-inner">
              <div class="title">Menu</div>
            </div>
          </div>
          <div class="page-content">
            <div class="block">
              <div class="list">
                <ul>
                  <li>
                    <a href="/minha_conta/" class="item-content item-link">
                      <div class="item-inner">
                        <div class="item-title">Questionário</div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="/relatorios/" class="item-content item-link">
                      <div class="item-inner">
                        <div class="item-title">Relatórios PDT</div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="/solicitacoes/" class="item-content item-link">
                      <div class="item-inner">
                        <div class="item-title">Solicitações ERGO</div>
                      </div>
                    </a>
                  </li>
                  <li>
                    <a href="/minha_conta/" class="item-content item-link">
                      <div class="item-inner">
                        <div class="item-title">Minha Conta</div>
                      </div>
                    </a>
                  </li>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>`

### Expected Behavior
Ripple animated buttons using the MD standard

### Actual Behavior
Button ripple animation on panel is "freezing", not returning to the default state. Home buttom too.

![localhost_3000_ galaxy s5](https://user-images.githubusercontent.com/3646493/40942217-dc9b56b6-6823-11e8-867e-6ca7a93a241a.png)
![localhost_3000_ galaxy s5 1](https://user-images.githubusercontent.com/3646493/40942218-dcbb58b2-6823-11e8-9928-4215b36eee05.png)
![localhost_3000_ galaxy s5 2](https://user-images.githubusercontent.com/3646493/40942220-dce011b6-6823-11e8-856c-e941fafa5bea.png)

**Comment by l41lt0n** [comment]
I have the same problem on my App.

:(

**Comment by EriveltonMS** [comment]
@l41lt0n , temporarily disable the ripple by changing the parameter in the app configuration

`  touch:{
    materialRipple:false,
  }`

with this the problem disappears, but the effect too.

**Comment by nolimits4web** [comment]
Do you see any errors in browser console?

**Comment by l41lt0n** [comment]
@nolimits4web 

For me it dont show nothing on the console. only the events Javascript not works.
It still freezed. so I need to close the app and reopen and it works again.

**Comment by EriveltonMS** [comment]
@nolimits4web , same from @l41lt0n, only freeze, no errors.

**Comment by l41lt0n** [comment]
@EriveltonMS,

I am doing test "materialRipple:false", for now everything is working.

for you it solve the problem?
the events is fired now?

Let's see the result :)

**Comment by l41lt0n** [comment]
@nolimits4web 

I think that problem is not on the framework7.

It start to happen when app go to background and stay there for a time.
I have the same issue on the iOS/Android

I have used materialRipple:false but the result is the same (only without animation/effect on the button), no javascript function is fired.

**Comment by dorad007** [comment]
I am experiencing the same problem too.
Thanks to god i have managed to somehow reproduce it. [JSFiddle](https://jsfiddle.net/0qduLeya/1/).
Instructions:
1. Use chrome
2. Open console
3. Tap like a crazy (swiping a little bit helps) inside the left link in the bottom.
* You may need to fit the iteration numbers in the loop inside "logics" function to your cpu skills. In my case 100 wasn't enough to reproduce the bug, whilst 10000 was too much.

**Comment by EriveltonMS** [comment]
I detected that my application had two initializations of the framework7, one of them without any option (remnant of the phonegap template). After removing one of them, the effect returned to work.

**Comment by dorad007** [comment]
@nolimits4web sent you a mail with a real reproduce.

**Comment by fdamore-xnoova** [comment]
same issue, tap like a crazy with chrome/desktop or chrome/mobile in every button with md effect

**Comment by fdamore-xnoova** [comment]
@EriveltonMS i used your code

touch:{ materialRipple:false, }

and the bug is fixed. the effect remain

**Comment by fdamore-xnoova** [comment]
@EriveltonMS sorry, i didnt fix by using your code. Instead i forgot a comma and i generate a syntax error. But with the syntax error the md effect works correctly! :-\

var app = new Framework7({
...
    view: {
        pushState: true,
    } //<-- comma missed
    touch:{ materialRipple:false, }
});

**Comment by fatihtkale** [comment]
is this fixed yet?

**Comment by dorad007** [comment]
Isn't fixed yet.[ 3.1.1 reproduce](https://jsfiddle.net/x93jozf5/1/).

**Comment by geoorg30** [comment]
I have same issue, and after inspection using chrome dev tools, i found the issue is caused by the panel-reveal overlay.
This blocks the UI with a transparent div.

**Comment by fatihtkale** [comment]
I found out it was because i had 2 linked Framework7 in my app.js file

**Comment by dorad007** [comment]
I think it worth fixing

**Comment by oleksandr-sovenko** [comment]
I have the same problem cordova + framework7, I noticed it happens when framework7 is working under cordova, but without cordova looks good. I can't understand why so :|.  I will use touch:{ materialRipple:false }

**Comment by mmis1000** [comment]
I actully can reproduce this on desktop by rapidly abuse click on tabbar buttons, unsure if it has the same cause though.

using desktop firefox, enable adaptability 12 menu, enale touch support, find a tabbar in  
https://framework7.io/kitchen-sink/core/?theme=md  
spam clicks very fast on it,  
it should freeze like this  

![default](https://user-images.githubusercontent.com/2993977/49681285-07793a80-fada-11e8-84a8-a13e42183a73.png)

**Comment by doradsoft** [comment]
Still happening in 3.6.5

**Comment by fatihtkale** [comment]
Guys check if you have framework7 implemtet twice in you app.js thats what fixed it for me.

**Comment by oleksandr-sovenko** [comment]
aah damn yes. might be. I noticed "twice initialization app.js" in my app too. But need to try remove now touch:{ materialRipple:false }. Thx.
